#TODO: change image name
kind: pipeline
type: docker
name: build

steps:
  - name: "build app"
    image: golang:1.14
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go get
      - go build -o skeleton
  - name: "build image"
    image: plugins/docker
    settings:
      repo: ptdmk/SKELETON
      tags:
        - dev-${DRONE_COMMIT_SHA:0:6}
        - dev-latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
  - name: "notification dingtalk"
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      message_color: true
      sha_link: false
      tpl: .dingtalk
      success_color: 34A853
      failure_color: EA4335
trigger:
  branch:
    - dev/master
  event:
    - push
---
kind: pipeline
type: docker
name: deploy dev

steps:
  - name: deploy_dev
    image: pelotech/drone-helm3
    settings:
      helm_command: upgrade
      chart: lwcharts/lifewood-golang
      release: skeleton-service
      api_server:
        from_secret: dev_k8s_api_url
      kubernetes_token:
        from_secret: dev_k8s_api_token
      namespace: lift-dev
      add_repos:
        - lwcharts=https://charts.lifewood.dev
      string_values:
        - subDomain=lift-dev.lifewood.dev/api/skeleton
        - containerImage=ptdmk/SKELETON:dev-${DRONE_COMMIT_SHA:0:6}
        - nginxPort=7000
trigger:
  branch:
    - dev/master
  event:
    - push